import './globals.css';
import type { Metadata } from 'next';
import type { NextFont } from 'next/dist/compiled/@next/font';
import { IBM_Plex_Mono } from 'next/font/google';
import type { JSX } from 'react';

const ibmPlexMono: NextFont = IBM_Plex_Mono({
  display: 'swap',
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: LayoutProps<'/'>): JSX.Element {
  return (
    <html className={`${ibmPlexMono.className} h-full antialiased`} lang="en">
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
